[package]
name = "exponential-histogram"
version = "0.2.1"
edition = "2024"

[lib]
bench = false

[[bench]]
name = "bench"
harness = false

[dependencies]
arc-swap                        = { version = "1.6" }
itertools                       = { version = "0.10" }
atomic_float                    = { version = "1.1.0" }

[dev-dependencies]
criterion                       = { version = "0.5" }
histogram                       = { version = "0.11" }
rand                            = { version = "0.8" }
